- name: copying mongo.repo to yum directory
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
  when: action == "present"

- name: installing mongodb server
  ansible.builtin.dnf:
    name: mongodb-org
    state: present
  when: action == "present"

- name: starting and enabling mongod service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: true
  when: action == "present"

- name: configuring mongod.conf
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1 '
    replace: '0.0.0.0'
  when: action == "present"
  notify: restarting mongod

- name: uninstalling mongod
  ansible.builtin.dnf:
    name: mongodb-org
    state: absent
  when: action == "absent"